#!/bin/bash
#
# Copyright (C) 2017 Ericsson India Global Services Pvt Ltd. and others.  All rights reserved..
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html
#
# Authors : Volker Luessem, Rihab Banday, Faseela K

#
# configuration parameters
#
#OUTFILE="/opt/cni/bin/cni-odl.log"

LOGFILE="/opt/cni/bin/cni-odl.log"
LAST_IP="/opt/cni/bin/last-ip"
IP_PREFIX="172.16.7."
BRIDGE="br1"
BRIDGE_IP="172.16.7.1"
#ELAN="kubecni"
CONTROLLER="{odl-ip}:8181"
ETCD="127.0.0.1:4001"
PARENTIF="parent1"
DIFFERENTIATOR="A"
no_proxy="{proxy}"
