# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'ipaddr'

vagrant_config = YAML.load_file("provisioning/virtualbox.conf.yaml")

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"

  # Spawn up the k8 master node
  config.vm.define "k8s-master" do |k8smaster|
    k8smaster.vm.hostname = "k8sMaster"
    k8smaster.vm.network "private_network", ip: vagrant_config['k8smaster']['overlay-ip']
    k8smaster.vm.network "private_network", ip: vagrant_config['k8smaster']['public-ip']
    k8smaster.vm.provision "shell", path: "provisioning/setup-Req.sh", privileged: false, :args => "#{vagrant_config['odl_ip']} #{vagrant_config['k8smaster']['overlay-ip']}"
    k8smaster.vm.provision "shell", path: "provisioning/setup-k8s-master.sh", privileged: false
    k8smaster.vm.provider "virtualbox" do |vb|
       vb.name = vagrant_config['k8smaster']['name']
       vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  # Spawn up the k8 minion1 node
  config.vm.define "k8s-minion1" do |k8sminion1|
    k8sminion1.vm.hostname = "k8sMinion1"
    k8sminion1.vm.network "private_network", ip: vagrant_config['k8sminion1']['overlay-ip'],auto_config: false
    k8sminion1.vm.network "private_network", ip: vagrant_config['k8sminion1']['public-ip']
    k8sminion1.vm.provision "shell", path: "provisioning/setup-Req.sh", privileged: false, :args => "#{vagrant_config['odl_ip']} #{vagrant_config['k8sminion1']['overlay-ip']}"
    
    k8sminion1.vm.provider "virtualbox" do |vb|
       vb.name = vagrant_config['k8sminion1']['name']
       vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  # Spawn up the k8 minion2 node
  config.vm.define "k8s-minion2" do |k8sminion2|
    k8sminion2.vm.hostname = "k8sMinion2"
    k8sminion2.vm.network "private_network", ip: vagrant_config['k8sminion2']['overlay-ip']
    k8sminion2.vm.network "private_network", ip: vagrant_config['k8sminion2']['public-ip']
    k8sminion2.vm.provision "shell", path: "provisioning/setup-Req.sh", privileged: false, :args => "#{vagrant_config['odl_ip']} #{vagrant_config['k8sminion2']['overlay-ip']}"
    k8sminion2.vm.provider "virtualbox" do |vb|
       vb.name = vagrant_config['k8sminion2']['name']
       vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
